name: nlp_test
channels:
  - anaconda
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - cudatoolkit==11.7
  - cudnn
  - pip==23.0.1
  - pip:
    - pyyaml==6.0
    - torch==1.13.0
    - torchvision==0.14.0
    - numpy==1.24.2
    - matplotlib==3.7.0
    - Pillow==9.4.0
    - pandas==1.5.3
    - easydict==1.10
    - scikit_learn==1.2.1
    - termcolor==2.2.0
    - checksumdir==1.2.0

